services:
  astrawiki:
    container_name: astrawiki
    build: .
    ports:
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
      - "31337:31337"
    volumes:
      - ./config:/usr/local/bin/share/config/
